train:
  project_name: "IIITPetsDataset"
  hyperparameters:
    epochs: 1
    patience: 5
    delta: 0.01
    learning_rate: 0.001
    image_longest_dimension: 256 # pixels
    batch_size: 1
    num_workers: 1
    encoder_name: "timm-efficientnet-b8"
    encoder_weights: "imagenet"
    in_channels: 3
    classes: 1
    loss_smoothing: 4
    mixed_precision: True
  loss:
    Jaccard:
      mode: "binary"
      from_logits: True
test:
  hyperparameters:
    image_longest_dimension: 256 # pixels
    batch_size: 1
    num_workers: 1
    classes: # Classes and their corresponding identity number. 0 is background.
      background: 0
      pets: 1