stages:
  compute_dataset:
    desc: This stage of the pipeline computes the dataset from a Labelstudio task.
    cmd: python3 code/compute_task_data.py --dataset data/labelstudio-pets-dataset.json --output data/computed/pets-dataset/
    deps:
    - code/compute_task_data.py
    - data/labelstudio-pets-dataset.json
    outs:
    - data/computed/pets-dataset/:
        cache: false
  train:
    desc: This stage of the pipeline trains the model.
    cmd: python3 code/train.py --dataset data/computed/pets-dataset/ --config ./control.yaml
    deps:
    - code/train.py
    - data/computed/pets-dataset/
    - ./control.yaml
    outs:
    - models/best_model.pth:
        cache: True
    - models/latest_model.pth:
        cache: True