stages:
  compute_dataset:
    desc: This stage of the pipeline computes the dataset from a Labelstudio task.
    cmd: python3 code/compute_task_data.py --dataset data/labelstudio-pets-dataset.json --output data/computed/pets-dataset/
    deps:
    - code/compute_task_data.py
    - data/labelstudio-pets-dataset.json
    outs:
    - data/computed/pets-dataset/
