name: minimal-pytorch
channels:
  - pytorch
  - conda-forge
dependencies:
  - mamba
  - python=3.10.*
  - pip
  - poetry
  - pytorch
  - torchvision
  - torchaudio

# Notes: 
# - install mamba, then install poetry packages, then install dvc[s3]
